### ISSUE TITLE
Enable back / cancel button when zooming in on a particular time period.

### ISSUE THREAD

**Issue by Popolechien** [kiwix/metrics#11]
In the Size of Backlog chart:
- Cool: I can zoom in on a particular date range by simply clicking on the chart.
- Uncool: there is no button nor indication to zoom out.

**Comment by kelson42** [comment]
@florentk Indeed! How to do that?

**Comment by florentk** [comment]
@kelson42 @Popolechien Yes is very annoying !

**Comment by florentk** [comment]
@kelson42 @Popolechien , in fact, just use the previous button of the navigator. In Kibana, all context is in the URL

**Comment by kelson42** [comment]
@florentk Good to me
