### ISSUE TITLE
Average time to solve does not look coherent.

### ISSUE THREAD

**Issue by Popolechien** [kiwix/metrics#12]
A picture is worth a thousand words, they say:
![Capture d’écran 2019-12-09 à 15 06 34](https://user-images.githubusercontent.com/21675885/70441918-90340900-1a95-11ea-942e-ef12a9ddc05e.png)

Also, we've been solving a lot more tickets recently (particularly on android) which should mechanically drag that average down. But not create a trough.

**Comment by kelson42** [comment]
@florentk Yes, something is wrong here.

**Comment by florentk** [comment]
@kelson42 I looking for use Studies in GrimoireELK to create specifics indices because, as for "opened issue", I can't get the evolution of theses metrics in ElasticSearch database to create the required graphs.

**Comment by florentk** [comment]
@kelson42 @Popolechien 
this graph is the average over a week of the number of days to resolve a ticket that was closed over this period.

**Comment by florentk** [comment]
@kelson42 I think that use also Studies for make that, I don't have the évolution of this metric in the database. #13

**Comment by florentk** [comment]
fix with https://github.com/kiwix/metrics/issues/13
