### ISSUE TITLE
Web site should have our logo/title

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#14]
favicon should be the one of Kiwix
Title should be something like "Kiwix development metrics"

**Comment by florentk** [comment]
the actual logo is in kibiter-6.1.4-1-linux-x86_64/src/ui/public/images/grimoire-dashboard.svg

**Comment by florentk** [comment]
reference of this file in :
```
src/core_plugins/kibana/public/dashboard/styles/index.less:  background-image: url("~ui/images/grimoire-dashboard.svg");
src/ui/public/chrome/directives/global_nav/global_nav.less:      background-image: url("~ui/images/grimoire-dashboard.svg");
```

**Comment by florentk** [comment]
You can now set title with `PROJECT_NAME` var env, and modify favicon in `favicon` subdir

**Comment by florentk** [comment]
done via be07658059aeff7f3ce68ac7da1abed3eb59387

**Comment by kelson42** [comment]
@florentk Can you please just configure it?
