### ISSUE TITLE
Number of lines commited (differenciation per contributor) is missing

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#27]
This is totally missing (in place we have other charts, but this is not what was required).

**Comment by florentk** [comment]
Is the graph "Number of added line & removed lines", no ?

**Comment by kelson42** [comment]
@florentk Where is the "differenciation per contributor"?

**Comment by florentk** [comment]
@kelson42 you select a or several authors in the list

**Comment by kelson42** [comment]
OK, Good to me
