### ISSUE TITLE
X axis granularity is not the best

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#30]
It seems the default duration of any point on the X axis is not optimal. Charts display a lot of points/bars because this point (duration) is really short. This is difficult to read the charts because of this.

It seems to display a day (even if I believe this an aggreate of values over many days). I don't think having more than 20-30 values on the X axis makes a lot of sense. To me depending of the overall period selected, we should display days/weeks/months smartly (but maybe we choose have somehow a chooser)? Or do we have an alternative approach?

**Comment by florentk** [comment]
@kelson42  I don't know how configure Kibana on agregation politic (how agregate on one week when one year interval ?), I don't found doc on this. But I can compute data on one week instead of one day. The drawback is we won't be able to "zoom" to see datas details for one day. :-/

**Comment by kelson42** [comment]
@florentk Could you please ask on the upstream repo. Without having this day/week/month/year granularity this is quite complex to compare and communicate about results.

**Comment by kelson42** [comment]
@florentk I don't really need this zoom feature. If X axis was easy to understand I could handle everything through the overall period.

**Comment by florentk** [comment]
fixed via 5c26bae28f9b6e3ff733872e26a45138f47a86b3 and https://github.com/florentk/grimoirelab-elk/commit/effc887b89f3b62460b148ef78376b7b0f675866
