### ISSUE TITLE
Time to solve should be differenciated

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#31]
* For bugs (tag "bug")
* For others (non-tag "bug")

**Comment by florentk** [comment]
@kelson42  Do you want deux curves (tag bug and no-bug) on the same graph or alows to select tag bug/no-bug as a filter ?

**Comment by florentk** [comment]
other alternativ : no show point, but just a curve to improve lisibility

**Comment by kelson42** [comment]
@florentk Not really happy with that idea

**Comment by florentk** [comment]
fixed via 5c26bae28f9b6e3ff733872e26a45138f47a86b3 and https://github.com/florentk/grimoirelab-elk/commit/effc887b89f3b62460b148ef78376b7b0f675866
