### ISSUE TITLE
Tune "Size of backlog" chart

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#33]
The numbers are more realistic now. Here a re few things I would like to do:
* Make it first in the list (top left)
* Title should be "Number of open tickets"
* Color for bugs should red (like in https://docs.servicenow.com/bundle/istanbul-performance-analytics-and-reporting/page/use/reporting/image/BarChart.png)
* Color for enhancement should be blue (like in https://docs.servicenow.com/bundle/istanbul-performance-analytics-and-reporting/page/use/reporting/image/BarChart.png)
* Bugs should be at the bottom and other at the top.
* Legend should be "bugs" and "others"

Then we should be good I guess with that chart.

**Comment by florentk** [comment]
@kelson42 , ok, but I don't know yet how to change the colors ...

**Comment by florentk** [comment]
done via cad431125e8cd35b6f6d125d885fa0d126ee9282

**Comment by kelson42** [comment]
Y axis title has not been fixed and I think the colors are not the blue and the red given in the example chart.

**Comment by kelson42** [comment]
It seems the title has been changed instead of the y axis title.... but the title was OK

**Comment by kelson42** [comment]
If possible would be good to have the color legend in the same order as the bars, “others” first.

**Comment by florentk** [comment]
@kelson42 is fixed for color and Y axis, but I can't change order of the legend

**Comment by florentk** [comment]
fix via 8ad38d11170325169d27cfd039edcc7a36761449

**Comment by kelson42** [comment]
@florentk You don't have fixed the title (bring back the old version). It should be "Size of the backlog"

**Comment by florentk** [comment]
doen via 9698889
