### ISSUE TITLE
Tunes "Number of tickets opened and closed"

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#34]
* Legend should be "opened" and "closed"
* Colors should be the same as on Github for an open (green) and closed (red) ticket
* Y axis legend should be "Number of tickets"
* I want things displayes in a form of curves
* A third "ratio" curve in black should show the opened - closed (so can be negative)

**Comment by florentk** [comment]
it's done, but the ratio is complex to be realised

**Comment by kelson42** [comment]
@florentk The point is that ultimately the ratio is interesting. Maybe there is a kind of chart which would make this ratio obvious?

**Comment by florentk** [comment]
@kelson42 I have create a graph for the ratio : "Evolution of open tickets", this is that ?

**Comment by kelson42** [comment]
@florentk I'm a bit unsure about the chart type but it's good for now. You have forgotten to fix the the Y axis legend.

**Comment by florentk** [comment]
@kelson42 , ok, but I have not exported the last dashboard, modifs are lost :(

**Comment by florentk** [comment]
done via 11d22d16dffc633cae0b51d88ec3b2113b3d2d76
