### ISSUE TITLE
Tune "Average time to solve"

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#35]
* Title should be "Time to solve"
* Y axis legend should "Average tickets lifetime (days)"
* Colors should be like in chart "Backlog size"
* Same bars as "Backlog size" should be used".

**Comment by florentk** [comment]
@kelson42  ok, but a same bar as "backlog size" has no sense because the sum of two average values is not a average value.

**Comment by kelson42** [comment]
@florentk Seems to be a pertinent remark. We should use curve then?

**Comment by florentk** [comment]
done via 9698889
