### ISSUE TITLE
Tune "Total lines of code"

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#36]
* Title should be "Size of codebase"
* Put "Total lines of code" un fourth position after "Average time to solve"
* Colors should come from https://docs.servicenow.com/bundle/istanbul-performance-analytics-and-reporting/page/use/reporting/image/BarChart.png
* Languages should be proper "Java", "C++", "Kotlin"
* Most common languages should be at the bottom
* Comments should not be counted (=deducted to the total number of lines) (but I don't want it to appear in the chart)

* Chart should be of type "area"
![image](https://user-images.githubusercontent.com/1029718/73206008-610b5100-4142-11ea-9997-873313fb0513.png)

**Comment by florentk** [comment]
I must resolve https://github.com/kiwix/metrics/issues/21 issue before to get values by file type. Do you want a pre defined list of langage or an list of language automatically deducted in relation to them the most used ?

**Comment by kelson42** [comment]
@florentk I want languages most used.

**Comment by florentk** [comment]
partialy done via a4138d2

**Comment by florentk** [comment]
> * Languages should be proper "Java", "C++", "Kotlin"
see python-libmagic

**Comment by florentk** [comment]
done via 9f80cbf5fac3bb19e936de0d0500f8a627cfb022
