### ISSUE TITLE
Problem with "Number of tickets opened and closed"

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#38]
There is never more tickets closed than opened. This is really strange... in particular if you consider that at the same time the overall number of tickets might decrease!?

**Comment by florentk** [comment]
@kelson42 in fact, I think that opened ticket curve is correct, but closed them is no correctly placed on Date axys. The date take in accound is the creation date of the ticket not the date of closing... If I set the Date axis as "closed date", the curve is good, but the the other curve of opened ticket is bad. Take the deux curves on the same graph is no possible.
It's complicated to fixed that, maybe I might create a other 'studie'.

**Comment by florentk** [comment]
@kelson42 Yes I think I might calculed that in a studie

**Comment by florentk** [comment]
@kelson42 I have drop this graph with add "Evolution of open tickets" them, it's ok for you ? Or I continue to dig the problem

**Comment by kelson42** [comment]
@florentk The number should be OK... if the KPI is not trustable, people won't use that tool. Please fix it.

**Comment by kelson42** [comment]
I think this ticket is oudated.
