### ISSUE TITLE
metrics.kiwix.org down

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#40]
I have configured HTTPs on Sloppy and restart the container... and now no content is available at all.

**Comment by florentk** [comment]
See https://github.com/kiwix/metrics/issues/18
And README.md :
> Initialization time : ~ 9 hours (cocom)

I have not use a volume because no space avaible

**Comment by kelson42** [comment]
@florentk How much storage would you need?

**Comment by florentk** [comment]
@kelson42 about 10 Go

**Comment by kelson42** [comment]
@florentk I will order more disk, so we can have this persistent volume

**Comment by florentk** [comment]
@kelson42 i still don't have extra disk space

**Comment by kelson42** [comment]
@florentk I have to do it tomorrow or in two days

**Comment by kelson42** [comment]
@florentk I have subsribed to more space, you should have now what you need
