### ISSUE TITLE
Last 7 days view seems wrong

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#41]
* Size of backlog is absolutely stable
* "Time to solve" and "Evolution of open tickets" are empty

**Comment by florentk** [comment]
We compute the values for one week, then is normal to have no value for the current week.  Else we should return at on day interval with many values ... 
On a other hand, no value for "Evolution of open tickets", even for the last 6 months, that is a bug !

**Comment by kelson42** [comment]
Why we don’t compute things for one day?

**Comment by florentk** [comment]
fix via 490b83a
