### ISSUE TITLE
build_grimoirelab script use no official grimoire-elk repository

### ISSUE THREAD

**Issue by florentk** [kiwix/metrics#45]
we adding github backlog study code in forks of [grimoirelab-elk](https://github.com/florentk/grimoirelab-elk) and [grimoirelab-sirmordred](https://github.com/florentk/grimoirelab-sirmordred). We need to integrate code in official repos or add a patch.

**Comment by florentk** [comment]
https://github.com/chaoss/grimoirelab-elk/issues/761

**Comment by florentk** [comment]
before pull request, add `reduced_labels` field of gituhub item

**Comment by florentk** [comment]
https://github.com/chaoss/grimoirelab-elk/pull/777

**Comment by kelson42** [comment]
@florentk Do you have a corresponding bug/feature ticket?

**Comment by florentk** [comment]
use https://github.com/chaoss/grimoirelab/releases/tag/0.2.38

**Comment by kelson42** [comment]
@florentk What is the status here? You have given a tag link, not a ticket?

**Comment by florentk** [comment]
fixed via https://github.com/chaoss/grimoirelab-elk/commit/39596eae4441815fda65ac8374e7fb4cd8781088 and 0759d72698ac2f0c9f44a96022db8dcc56aa279d
