### ISSUE TITLE
Number of code/ticket contributors improvments

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#54]
* Y axis labels should "Number of code contributors" and "Number of tickets participants"
* Title should be "Code contributor team size"
* Title should be "Ticket participant team size"

**Comment by florentk** [comment]
I'm going to watch this, but it seemed too complicated to do

**Comment by florentk** [comment]
fixed via 1d54e5873ba19b132da3ef007c66c6be48252b3f
