### ISSUE TITLE
"Evolution of open tickets" is totally empty for the last 7 days!

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#55]
https://metrics.kiwix.org/app/kibana#/dashboard/Overview?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(description:'Overview%20Panel%20by%20Kiwix',filters:!(('$state':(store:appState),meta:(alias:'Empty%20Commits',disabled:!f,index:git,key:files,negate:!t,params:(query:'0',type:phrase),type:phrase,value:'0'),query:(match:(files:(query:'0',type:phrase)))),('$state':(store:appState),meta:(alias:Bots,disabled:!f,index:git,key:author_bot,negate:!t,params:(query:!t,type:phrase),type:phrase,value:!t),query:(match:(author_bot:(query:!t,type:phrase))))),fullScreenMode:!f,options:(darkTheme:!f,useMargins:!t),panels:!((gridData:(h:3,i:'37',w:6,x:0,y:9),id:f62d9e20-184b-11ea-8930-836c4cc0aa6f,panelIndex:'37',type:visualization,version:'6.1.4-1'),(gridData:(h:3,i:'40',w:6,x:6,y:0),id:bc6428d0-2bbf-11ea-b387-dfc81c1b31f0,panelIndex:'40',title:Filters,type:visualization,version:'6.1.4-1'),(gridData:(h:3,i:'41',w:6,x:6,y:3),id:'9740f5d0-2d4d-11ea-b387-dfc81c1b31f0',panelIndex:'41',type:visualization,version:'6.1.4-1'),(gridData:(h:3,i:'43',w:6,x:6,y:9),id:'1b35a160-2d4e-11ea-b387-dfc81c1b31f0',panelIndex:'43',type:visualization,version:'6.1.4-1'),(gridData:(h:3,i:'44',w:6,x:6,y:12),id:'95a63c20-2d4e-11ea-b387-dfc81c1b31f0',panelIndex:'44',type:visualization,version:'6.1.4-1'),(gridData:(h:3,i:'46',w:6,x:6,y:6),id:'6e710420-2eff-11ea-b7fb-dfaec3b825cc',panelIndex:'46',type:visualization,version:'6.1.4-1'),(gridData:(h:3,i:'50',w:6,x:0,y:3),id:'2ecb82b0-3bb5-11ea-95ab-5b7a00a159a1',panelIndex:'50',type:visualization,version:'6.1.4-1'),(gridData:(h:3,i:'51',w:6,x:0,y:0),id:a69b2940-3bb4-11ea-95ab-5b7a00a159a1,panelIndex:'51',type:visualization,version:'6.1.4-1'),(gridData:(h:3,i:'52',w:6,x:0,y:6),id:'6bf4b060-4201-11ea-8e3d-7f382b9d1c83',panelIndex:'52',type:visualization,version:'6.1.4-1'),(gridData:(h:3,i:'53',w:6,x:0,y:12),id:cf5abac0-765c-11ea-8fbd-d11a01cd3307,panelIndex:'53',type:visualization,version:'6.1.4-1')),query:(language:lucene,query:(query_string:(analyze_wildcard:!t,default_field:'*',query:'*'))),timeRestore:!t,title:Overview,uiState:(P-47:(spy:(mode:(fill:!f,name:!n)),vis:(params:(config:(searchKeyword:''),sort:(columnIndex:!n,direction:!n)))),P-48:(vis:(legendOpen:!t)),P-51:(vis:(legendOpen:!t)),P-53:(vis:(colors:('Aditya%20Sood':%23B7DBAB,'Emmanuel%20Engelhart':%230A50A1,'Geoffrey%20Kantaris':%23DEDAF7,'Isaac%20Hutt':%23BF1B00,'Joseph%20Reeve':%23F9934E,'Justin%20Biggs':%23705DA0,'Matthieu%20Gautier':%23508642,'Sean%20Mac%20Gillicuddy':%23967302,'Travis%20Briggs':%23D683CE,'renaud%20gaudin':%236ED0E0)))),viewMode:view)

**Comment by florentk** [comment]
The real problem is the bar graph interval. The number of opened ticket is computed all days. But when we choose last 7 days, the interval bar graph is  beside 1 days (in your case is 12 hours). Then, one value on two are missing for the number of opened tickets. The consequence is a bad value for the derivate (evolution of open tickets), and a graph empty. I would like define a minimum interval to 1 day, but I can't find this parameter.

**Comment by kelson42** [comment]
@florentk Maybe we should create a ticket upstream?

**Comment by kelson42** [comment]
@florentk OK, you can open a ticket if you want... on my side I think I can live with that, at least for the moment.
