### ISSUE TITLE
Add missing repository

### ISSUE THREAD

**Issue by rgaudin** [kiwix/metrics#56]
A few recently created repos appear to be missing on metrics:

* https://github.com/openzim/python-libzim
* https://github.com/openzim/python_scraperlib
* https://github.com/openzim/nautilus
* https://github.com/openzim/education-numerique
* https://github.com/kiwix/python_storagelib

**Comment by kelson42** [comment]
@florentk Would you be able to quickly fix this please?

**Comment by florentk** [comment]
@rgaudin yes. As shown in README, you have to add this repos in https://github.com/kiwix/metrics/blob/master/config/projects.json

**Comment by florentk** [comment]
fix in https://github.com/kiwix/metrics/commit/7cfe8bc203858b20d54e55210d7a256042486aef

**Comment by kelson42** [comment]
@florentk thank you. Next time we will do it ourself.

**Comment by kelson42** [comment]
Je ne vois toujours pas nautilus sur metrics.kiwix.org :(

**Comment by florentk** [comment]
@kelson42 I forgot to restart the instance

**Comment by kelson42** [comment]
OK, thx
