### ISSUE TITLE
System is down

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#57]
@florentk Can you please have a look?

**Comment by kelson42** [comment]
@florentk I have restarted it and put a bit more memory. Hopefuly this was the reason of the elasticsearch crash.

**Comment by kelson42** [comment]
@florentk I have to reopen this bug, this is again down and I fail to restart it. Would you please be able to look at it and tell me why it periodically just dies and can not recover?

**Comment by florentk** [comment]
related #62 #63

**Comment by florentk** [comment]
with #62 #63 you can restart easly if system down
