### ISSUE TITLE
Attribute author_org_name is Unknown

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#6]
It should have Kiwix and openZIM

**Comment by florentk** [comment]
Ok, but project will be "unknown" ? Or we need organize our repositories in several projets in two organizations.

**Comment by florentk** [comment]
I thing we should add kiwix and openZIM in orgs.json config file

**Comment by florentk** [comment]
In GrimoireLab, organisation concern an author, it's set with the domain name of e-mail address. We not use this in our dashboard.  

On an other hand, we had `project` field in the databse. This field is not a project in github, but a set of repositories specified in `projects.json`. We will use this to define an organisation in our dashboard.

**Comment by florentk** [comment]
The enriched index contains the attribute author_org_name, which includes the name of the organization.

We have just Unknown entries in our instance (https://metrics.kiwix.org/goto/293e5dabd5bda074de671c4c2dcf8c1c). We can either add organizations via:

hatstall (https://github.com/chaoss/grimoirelab/blob/master/docker-compose/docker-compose.yml#L12) or
modifying the organizations.json and restart the container.

https://github.com/chaoss/grimoirelab-elk/pull/777#discussion_r378398479

**Comment by kelson42** [comment]
@florentk Not sure about the status here, it seems fixed?

**Comment by kelson42** [comment]
I believe we are not impacted visually by this.
