### ISSUE TITLE
cocom_chaoss_study add multiple entry for each language

### ISSUE THREAD

**Issue by florentk** [kiwix/metrics#60]
In begin of month, the Size of codebase anormaly decrease

**Comment by florentk** [comment]
After a incrémentale update, the number of duplicate is inferior in comparison with previous month, hence the anormaly decrease of size of codebase

**Comment by kelson42** [comment]
https://github.com/chaoss/grimoirelab-elk/issues/899 is fixed.

**Comment by florentk** [comment]
fixed with 6ea9c8d by update to 0.2.54 release version

**Comment by kelson42** [comment]
@florentk thx, don't forget to redeploy the container please

**Comment by florentk** [comment]
@kelson42 yes is done
