### ISSUE TITLE
python-scraperlib repo URL is incorect

### ISSUE THREAD

**Issue by florentk** [kiwix/metrics#70]
In the project file dash is used (python-scraperlib) as the Github repo name use a underline char (python_scraperlib)

**Comment by kelson42** [comment]
@rgaudin There was a reason why this specific repo has an underscore whereas all other have a dash?

**Comment by rgaudin** [comment]
No, the project is called `zimscraperlib`. I remember you specifically requesting the repo to have a `python` prefix but there's no reason for that `_` vs a `-`. Renaming it would have no consequence beside requiring devs to change the origin url.

**Comment by kelson42** [comment]
Repo has been renamed
