### ISSUE TITLE
Implement Dashboard with following KPI

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#8]
KPIS:
* Size of the backlog (number of tickets with the status open, differentiation of label "bug" from other)
* Number of tickets opened and closed
* Size of of code base in lines with (differentiation per language)
* Number of lines commited (differenciation per contributor)
* Number of code contributors/committers (in the last period)
* Average to ticket time to solve (differenciation bugs from others)
* Number of ticket participants
* Number of releases (in the last period)
 
Remarks:
* All the stats are over time (period of 1 days or 1 month, ...) in x axis.
* This KPIs are global (all openzim+kiwix repos together), but each KPI should be computable for one or many selected repos.

--------------------

25 november
-----------
Allow to add new "visualisations" in docker image (needed for new KPIs)
Allow to init Overviews panel on container creation from a config file
Create a new "overview" panel with first KPIs:
- Size of backlog
- Number of tickets opened and closed
- Average to ticket time to solve
- Number of added line & removed lines

9 december
----------
Integrate Graal to docker image
Add the KPI "Size of code base in lines" to owerview panel

16 december
-----------
Add other KPIs :
- Number of code contributors/committers
- Number of ticket authors
- Number defined tags

23 december
-----------
Allow to easily use the panel interface to choose differentiation :
- code language
- label (bug, enhancement ...)
- organisation (kiwix/openzim)
- contributor
- period

**Comment by kelson42** [comment]
@florentk Does that sounds doable for you?

**Comment by florentk** [comment]
> KPIS:
> 
> * Size of the backlog (number of tickets with the status open, differentiation of label "bug" from other)
For me this is the number of created issue subtract by the number of closed issue.

> * Number of tickets opened and closed
what is the interval : daily ? weekly ? monthly ?

> * Size of of code base in lines with (differentiation per language)
ok

> * Number of lines commited (differenciation per contributor)
this is the number of added line ? the removed lines ? both ?
interval ?

> * Number of code contributors/committers (in the last period)
How you define "the last period" ?

> * Average to ticket time to solve (differenciation bugs from others)
ok

> * Number of ticket participants
ok for the number of ticket authors (submitters)

> * Number of releases (in the last period)
I have not this metric, but i have the number of tag, it is ok ?

What is the type of visualization for each KPI ? (uniq value ? line ? bar ?)

**Comment by Popolechien** [comment]
Also, would it be possible to have a means of comparison, ie selecting the time period ? Ultimately I'd like to compare Year1 KPIs with Year2, 3 or 4.

**Comment by florentk** [comment]
Yes, for all dashboard, you can globaly select manualy a time période.

**Comment by florentk** [comment]
See milestones

**Comment by kelson42** [comment]
I reopen it as I have no way to get that list with requirements the way the milestones have been made.

**Comment by kelson42** [comment]
@florentk So I have share we you the last tuning stuff for the 4 first top important charts. Hopefully this is doable. Then we should really have a look to the periodicity problem. Then we could close milestone 1.
